title: A blog of small things
description: Hi there, this is a blog by Abhijeet Ghawade, an undergraduate student of IIT Madras. 
show_downloads: false

baseurl: "/cayman-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://abhijeetg12.github.io/cayman-blog/" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Abhijeet Ghawadet"
image: /thumbnail-jumbo.png
twitter:
  username: @abhijeetg1997
#  site:
facebook:
  #publisher: 1592372034171500
  profile_id: 100009262104229
  #app_id: 1798910940422432 # cayman-blog
  #authors: Abhijeet Ghawade
#  admins:
